"""empty message

Revision ID: 49993938734f
Revises: 4c3f64d56432
Create Date: 2018-01-14 12:32:00.613742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49993938734f'
down_revision = '4c3f64d56432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('ground_truth', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('prediction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'prediction')
    op.drop_column('report', 'ground_truth')
    # ### end Alembic commands ###
