"""empty message

Revision ID: 4c3f64d56432
Revises: f67201769be1
Create Date: 2018-01-14 01:40:33.775827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3f64d56432'
down_revision = 'f67201769be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('img_id', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_report_img_id'), 'report', ['img_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_img_id'), table_name='report')
    op.drop_column('report', 'img_id')
    # ### end Alembic commands ###
