"""reporting table

Revision ID: 78b22ef381af
Revises: 638db9ae55da
Create Date: 2018-01-12 22:48:50.073606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b22ef381af'
down_revision = '638db9ae55da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pneumonia', sa.String(length=32), nullable=True),
    sa.Column('consolidation', sa.Boolean(), nullable=True),
    sa.Column('infiltrates', sa.Boolean(), nullable=True),
    sa.Column('atelectasis', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_pneumonia'), 'report', ['pneumonia'], unique=False)
    op.create_index(op.f('ix_report_timestamp'), 'report', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_timestamp'), table_name='report')
    op.drop_index(op.f('ix_report_pneumonia'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
