"""empty message

Revision ID: bf7ca3599683
Revises: 
Create Date: 2018-01-15 15:52:22.117820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7ca3599683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('remember_me', sa.Boolean(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_date_registered'), 'user', ['date_registered'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_id', sa.String(length=320), nullable=True),
    sa.Column('pneumonia', sa.String(length=32), nullable=True),
    sa.Column('consolidation', sa.String(length=32), nullable=True),
    sa.Column('infiltrates', sa.String(length=32), nullable=True),
    sa.Column('atelectasis', sa.String(length=32), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ground_truth', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_img_id'), 'report', ['img_id'], unique=False)
    op.create_index(op.f('ix_report_pneumonia'), 'report', ['pneumonia'], unique=False)
    op.create_index(op.f('ix_report_timestamp'), 'report', ['timestamp'], unique=False)
    op.create_table('user_profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=160), nullable=True),
    sa.Column('middle_name', sa.String(length=160), nullable=True),
    sa.Column('last_name', sa.String(length=160), nullable=True),
    sa.Column('npi', sa.Integer(), nullable=True),
    sa.Column('doctor', sa.String(length=32), nullable=True),
    sa.Column('radiologist', sa.String(length=32), nullable=True),
    sa.Column('training', sa.String(length=32), nullable=True),
    sa.Column('clinical_practice', sa.String(length=32), nullable=True),
    sa.Column('clinical_specality', sa.String(length=32), nullable=True),
    sa.Column('institution_type', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('npi')
    )
    op.create_index(op.f('ix_user_profile_timestamp'), 'user_profile', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_timestamp'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_report_timestamp'), table_name='report')
    op.drop_index(op.f('ix_report_pneumonia'), table_name='report')
    op.drop_index(op.f('ix_report_img_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_date_registered'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
